# Generated by Django 4.2 on 2024-07-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('course', '0002_department_course_slug_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='department.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
