# Generated by Django 4.2 on 2024-07-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_lesson_course'),
        ('enrollment', '0004_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.lesson', unique=True),
        ),
    ]
